GlobalBaseUrl: https://api.cosmos.network
LocalBaseUrl:  http://localhost:1317
LocalAccount1Address: cosmos1ht7y9zx4n4wnvwmgyqm8309xj2yulwklj54h5j
LocalAccount2Address: cosmos1235em592dc22gehs9z44reqtuy2hqulndd54zt
LocalAccount1PrivateKey: |-
  -----BEGIN TENDERMINT PRIVATE KEY-----
  kdf: bcrypt
  salt: C586A3498B0298905ABE7D6DBADBCB87

  FascN+0QNtdvs/Wh3PzxwHBNmPr5nh+yZA3g4aJD6CHbOPLCYnD7ozt4sZW3LvQu
  Zs2mQ5J0t9siMmKCi/1RZ0CoweBz0pUKvO8Kqek=
  =K7Bt
  -----END TENDERMINT PRIVATE KEY-----
LocalAccount1Passphrase: 11111111
LocalChainId: testing
LocalDelegator1Address: cosmos18cqk9yh9alcf54fvprqwaa96d4mu65c0aw4suv
LocalValidatorAddress: cosmosvaloper1ht7y9zx4n4wnvwmgyqm8309xj2yulwklhqpzcp
GlobalDelegator1Address: cosmos14t3dh3ucxjfey6akem75q9atydz3zg5cynepds
GlobalValidator1Address: cosmosvaloper1ey69r37gfxvxg62sh4r0ktpuc46pzjrm873ae8
GlobalValidator2Address: cosmosvaloper156gqf9837u7d4c4678yt3rl4ls9c5vuursrrzf
GlobalChainId: cosmoshub-3
CutLongOutput: false
  